spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo_application
      auto-index-creation: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    password: admin
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true
  application:
    name: "demo application"
logging:
  level:
    org:
      springframework: debug
server:
  port: 3030

