spring:
  cache:
    type: redis
  data:
    mongodb:
      host: localhost
      port: 27017
      database: demo_application
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/demo
    password: admin
    username: admin
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  threads:
    virtual:
      enabled: true
  application:
    name: "demo application"
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework: debug
server:
  port: 3030
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1
    enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, info
  endpoint:
    metrics:
      access: read_only
  metrics:
    enable:
      all: true
  prometheus:
    metrics:
      export:
        enabled: true
clientPermissionFilter:
  enabled: false